### ISSUE TITLE
apply-js-mixin approach is not friendly to advanced compilation mode

### ISSUE THREAD

**Issue by ul** [aaronc/freactive.core#1]
and requires externs to work. Trying to use `.addInvalidationWatch` produces in advanced mode `Uncaught TypeError: $rx$$1$$.$addInvalidationWatch$ is not a function` (pseudo-names enabled for clarity, w/o it error is `c.fl is not a function` ;-)

**Comment by aaronc** [comment]
Thanks for catching this! I'll push a fix asap.

On Fri, Jun 12, 2015 at 1:43 AM, Ruslan Prokopchuk <notifications@github.com

**Comment by aaronc** [comment]
Should be fixed in 1ad9a02b0651bb8c506d541633812079432f715a. Let me know if you encounter any other issues with advanced compilation.

**Comment by ul** [comment]
I have no errors in advanced compilation mode with the latest master, thank you!. Would you mind pushing snapshot to clojars?
