### ISSUE TITLE
Cutting out 0.2.0-alpha2

### ISSUE THREAD

**Issue by ul** [aaronc/freactive.core#3]
Do you feel that current version is ready to be 0.2.0-alpha2? Or may be right after #2 fix? I'm going to use `freactive.core` as the basis for data derivation flow in commercial project and to rely on at least alpha cuts is much more better than snapshots (and alpha1 is outdated to use).

**Comment by aaronc** [comment]
Yeah, I think we're pretty close to alpha2. The only thing is that I still have a few things to tweak in core before 0.2.0 and any testing others can do on snapshots is helpful - although I guess I could just push alpha3 when I'm ready for further testing. The pending changes shouldn't change the API at all except with regards to the experimental projections code.

**Comment by ul** [comment]
Okay, thanks for the answer and for freactive!

**Comment by aaronc** [comment]
You're welcome!
